name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2.5.0
    - name: Build the Docker image
      env:
        PAE_SENSOR_IDS: ${{ secrets.PAE_SENSOR_IDS }}
        PAE_API_READ_KEY: ${{ secrets.PAE_API_READ_KEY }}
      run: docker build . --file Dockerfile -t purpleair_exporter:$(date +%s)
      
    - uses: docker/build-push-action@v4.0.0
      with:
        build-args: --progress plain
        platforms: linux/amd64,linux/arm64
